language: node_js
node_js:
  - 0.6
before_script:
  - "git submodule update --init"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "phantomjs bin/phantomjs.js"
  - "nodelint src/backbone.mutators.js"